### ISSUE TITLE
make examples not packages 

### ISSUE THREAD

**Issue by adsick** [parasyte/pixels#243]
I'm not sure why is it done this way, maybe you have some reasons but cargo supports examples out of the box, why not just use it?

**Comment by parasyte** [comment]
The short answer is that Cargo's dependency management is not the best when it comes to examples that don't share dependencies with the main crate (or each other). Bundling everything into a single package for all the examples means that `[dev-dependencies]` is going to include everything that all of the examples depend on. The full list at present would end up something like this:

```toml
[dev-dependencies]
log = "0.4"
winit = "0.25"
winit_input_helper = "0.10"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
beryllium = { version = "0.3", features = ["extern_crate_raw_window_handle"] }
byteorder = "1.3"
egui = "0.15"
egui_wgpu_backend = "0.14"
egui-winit = { version = "0.15", default-features = false, features = ["links"] }
env_logger = "0.9"
euclid = "0.22"
fltk = { version = "1.2", features = ["raw-window-handle", "no-images", "no-pango"] }
getrandom = "0.2"
gilrs = "0.8"
imgui = "0.8"
imgui-wgpu = "0.18"
imgui-winit-support = { version = "0.8", default-features = false, features = ["winit-25"] }
line_drawing = "1.0"
randomize = "3.0"
raqote = { git = "https://github.com/jrmuizel/raqote.git", rev = "dea376474966fe91f0fa3c5115171e0df86bac22", default-features = false }
simple-invaders = { path = "examples/invaders/simple-invaders" }
```

Note that none of these dependencies are needed by `pixels` or its tests. These are specifically dependencies that various examples need.

The implication is that in order to build any example, the user would have to build `sdl2` and `fltk`. Except for the WASM build, anyway... Only one of the examples even supports WASM, so not all examples will build for it. Not the end of the world, but so awkward it isn't even funny.

----

The long answer is that this repo started out using cargo examples. It used features to try to isolate the examples from one another to avoid the dependency aggregate problem described above. See #63 for some context. We finally switched over to a workspace with individual example packages in #67.

The specific tracking issue in Cargo has been open for 6 years: https://github.com/rust-lang/cargo/issues/1982. The discussion is long, difficult to follow, and very little (if any) progress has been made on it. Trying to make Cargo's support for examples work with something it wasn't designed to handle would be strictly worse than what we have today.

Workspaces have their own problems, but we avoid them by not using a virtual manifest and by keeping our feature requirements to a minimum.  A workspace with individual packages can be manageable, while dependencies with examples is currently not manageable.
