### ISSUE TITLE
raw_window_handle old version

### ISSUE THREAD

**Issue by noniwoo** [parasyte/pixels#401]
In your repo I can clearly see that current version is using raw-window-handle = "0.6", but on https://crates.io/crates/pixels/0.14.0/dependencies you can see, that it uses raw-window-handle v0.5. Could you please update the crate to make pixels interoperable with current version of winit?

**Comment by XeanYu** [comment]
I also encountered this issue. Currently, HasRawWindowHandle has been deprecated and replaced with HasWindowHandle. winit has also adopted HasRawWindowHandle. Could you please update this as soon as possible? Much appreciated.

**Comment by parasyte** [comment]
`pixels` 0.14 was released with support for `wgpu` 0.17. If you want a newer version of `wgpu` with `raw-window-handle` 0.6 then you need to use the git repo (which supports `wgpu` 0.19) until another release is published:

```toml
[dependencies.pixels]
git = "https://github.com/parasyte/pixels.git"
rev = "57d339e61edd3ce3233cce47546382ee0f7bea06"
```
