### ISSUE TITLE
x11 lib needed, perhaps this to install instructions?

### ISSUE THREAD

**Issue by Ran4** [parasyte/pixels#83]
Users of this library is likely to stumble upon this issue, at least in linux environments.

https://github.com/servo/rust-xlib/issues/44

It's trivially fixable with `sudo apt install libx11-dev` and easily googleable, but perhaps adding this to README.md could be helpful?

**Comment by parasyte** [comment]
Is this a build dependency for the crate, or for the examples?

**Comment by parasyte** [comment]
From a quick survey, it seems like this is actually a bug in the depths of `wgpu`. See the linked issue for details.

I'm happy to document the required dependency, but in the future I would be more interested in documenting how to disable the requirement by setting a feature flag. ;)

**Comment by parasyte** [comment]
The upstream issue has been resolved, and consumers of `wgpu` will be able to opt-in to `libx11` if they need it, using something like the following `Cargo.toml` entry:

```toml
[target.'cfg(all(unix, not(target_os = "ios"), not(target_os = "macos")))'.dependencies]
gfx-backend-vulkan = { version = "0.5", features = ["x11"] }
```

I'll leave this ticket open to track the documentation work... which won't be viable to begin until we update `wgpu`.
